import Head from 'next/head'
import { Inter } from 'next/font/google'
import Headers from '@/Components/Headers'
import Main from '@/Components/MainPage'
import main from "../styles/Main.module.css"
import { useSelector } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const theme = useSelector((state: any) => state.data.theme); //calling for theme state using REDUX

  return (
    <div style={{overflow : "hidden" , backgroundColor:"var(--color-bg)"}} className={theme === 'light' ? main.light : main.dark}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
    </div>
  )
}
